# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_upvotes', models.IntegerField(default=0, help_text='Total upvotes')),
                ('total_downvotes', models.IntegerField(default=0, help_text='Total downvotes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date updated')),
                ('answer', models.TextField(help_text='Enter your answer')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_contributor', to=settings.AUTH_USER_MODEL)),
                ('downvoted_by_users', models.ManyToManyField(related_name='answer_downvoted_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_upvotes', models.IntegerField(default=0, help_text='Total upvotes')),
                ('total_downvotes', models.IntegerField(default=0, help_text='Total downvotes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date updated')),
                ('subject', models.CharField(help_text='Enter the subject of the question.', max_length=200)),
                ('description', models.TextField(help_text='Enter the description of your question.')),
                ('category', models.ForeignKey(blank=True, help_text='Choose category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.Category')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_contributor', to=settings.AUTH_USER_MODEL)),
                ('downvoted_by_users', models.ManyToManyField(related_name='question_downvoted_by_users', to=settings.AUTH_USER_MODEL)),
                ('upvoted_by_users', models.ManyToManyField(related_name='question_upvoted_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Select question', on_delete=django.db.models.deletion.CASCADE, to='qa.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by_users',
            field=models.ManyToManyField(related_name='answer_upvoted_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
