# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_answerrating_questionrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='answerrating',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerrating',
            name='contributer',
        ),
        migrations.RemoveField(
            model_name='questionrating',
            name='contributer',
        ),
        migrations.RemoveField(
            model_name='questionrating',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, help_text='Rate the answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, help_text='Rate the question'),
        ),
        migrations.DeleteModel(
            name='AnswerRating',
        ),
        migrations.DeleteModel(
            name='QuestionRating',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.Category'),
        ),
    ]
