# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20180210_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='contributer',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='contributer',
            new_name='contributor',
        ),
    ]
