# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0010_auto_20180212_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, help_text='Rate the question')),
                ('question', models.ForeignKey(help_text='Select question', on_delete=django.db.models.deletion.CASCADE, to='qa.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
