# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_ratequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='ratequestion',
            name='rating',
            field=models.BooleanField(help_text='Rate the question'),
        ),
    ]
