# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0015_auto_20180226_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='rateanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ratequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='ratequestion',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoted_by_users',
            field=models.ManyToManyField(related_name='answer_downvoted_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='total_downvotes',
            field=models.IntegerField(default=0, help_text='Total downvotes'),
        ),
        migrations.AddField(
            model_name='answer',
            name='total_upvotes',
            field=models.IntegerField(default=0, help_text='Total upvotes'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by_users',
            field=models.ManyToManyField(related_name='answer_upvoted_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='downvoted_by_users',
            field=models.ManyToManyField(related_name='question_downvoted_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='total_downvotes',
            field=models.IntegerField(default=0, help_text='Total downvotes'),
        ),
        migrations.AddField(
            model_name='question',
            name='total_upvotes',
            field=models.IntegerField(default=0, help_text='Total upvotes'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvoted_by_users',
            field=models.ManyToManyField(related_name='question_upvoted_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RateAnswer',
        ),
        migrations.DeleteModel(
            name='RateQuestion',
        ),
    ]
